name: Build and Deploy Code

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code from GitHub
        uses: actions/checkout@v2
      - name: Confirm Python version
        run: python --version